# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'active_zhuce.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ZhuceWindow(object):
    def setupUi(self, ZhuceWindow):
        ZhuceWindow.setObjectName("ZhuceWindow")
        ZhuceWindow.resize(550, 348)
        self.centralwidget = QtWidgets.QWidget(ZhuceWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.get_verification_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_verification_button.setGeometry(QtCore.QRect(340, 70, 102, 31))
        self.get_verification_button.setObjectName("get_verification_button")
        self.zc_active_button = QtWidgets.QPushButton(self.centralwidget)
        self.zc_active_button.setGeometry(QtCore.QRect(240, 230, 91, 41))
        self.zc_active_button.setObjectName("zc_active_button")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 50, 271, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tel_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.tel_label.setObjectName("tel_label")
        self.horizontalLayout.addWidget(self.tel_label)
        self.tel_line = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.tel_line.setEnabled(True)
        self.tel_line.setObjectName("tel_line")
        self.tel_line.setPlaceholderText("Please enter your telphone number")
        self.horizontalLayout.addWidget(self.tel_line)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 140, 271, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verification_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.verification_label.setObjectName("verification_label")
        self.horizontalLayout_2.addWidget(self.verification_label)
        self.verification_line = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.verification_line.setEnabled(True)
        self.verification_line.setObjectName("verification_line")
        self.horizontalLayout_2.addWidget(self.verification_line)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(340, 120, 169, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.choose_tuokuai = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.choose_tuokuai.setObjectName("choose_tuokuai")
        self.verticalLayout.addWidget(self.choose_tuokuai)
        self.manual_verification = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.manual_verification.setObjectName("manual_verification")
        self.verticalLayout.addWidget(self.manual_verification)
        self.auto_verification = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.auto_verification.setObjectName("auto_verification")
        self.verticalLayout.addWidget(self.auto_verification)
        ZhuceWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ZhuceWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 23))
        self.menubar.setObjectName("menubar")
        ZhuceWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ZhuceWindow)
        self.statusbar.setObjectName("statusbar")
        ZhuceWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ZhuceWindow)
        QtCore.QMetaObject.connectSlotsByName(ZhuceWindow)

    def retranslateUi(self, ZhuceWindow):
        _translate = QtCore.QCoreApplication.translate
        ZhuceWindow.setWindowTitle(_translate("ZhuceWindow", "注册页面"))
        self.get_verification_button.setText(_translate("ZhuceWindow", "获取验证码"))
        self.zc_active_button.setText(_translate("ZhuceWindow", "注册"))
        self.tel_label.setText(_translate("ZhuceWindow", "手机号："))
        self.verification_label.setText(_translate("ZhuceWindow", "验证码："))
        self.choose_tuokuai.setText(_translate("ZhuceWindow", "托块验证方式："))
        self.manual_verification.setText(_translate("ZhuceWindow", "手动托块验证(推荐)"))
        self.auto_verification.setText(_translate("ZhuceWindow", "自动托块验证(通过率较低)"))
